import html
from datetime import datetime, timezone


def _esc(s):
    return html.escape(str(s))


def _section(title, rows, accent="#38d1d7"):
    if not rows:
        return ""
    items = "\n".join(f"<li>{r}</li>" for r in rows)
    return (f'<section><h2 style="border-left:3px solid {accent}">{_esc(title)} '
            f'<span class="count">{len(rows)}</span></h2><ul>{items}</ul></section>')


def render_report(target, ex, origins=None):
    origins = origins or {}

    def src(cat, key):
        files = origins.get((cat, key))
        if not files:
            return ""
        files = sorted(files)
        tag = files[0] + (f" +{len(files)-1}" if len(files) > 1 else "")
        return f' <span class="src">&larr; {_esc(tag)}</span>'

    sev_color = {"high": "#e44628", "medium": "#d8a800", "low": "#7a7a80"}

    secrets = [f'<span class="bad">{_esc(l)}</span>: <code>{_esc(r)}</code>{src("secrets", r)}'
               for l, r in sorted(ex.secrets)]
    cloud = [f'<span class="bad">{_esc(l)}</span>: <code>{_esc(v)}</code>{src("cloud", v)}'
             for l, v in sorted(ex.cloud)]
    weaknesses = []
    for sev, label in sorted(ex.weaknesses, key=lambda w: {"high": 0, "medium": 1, "low": 2}.get(w[0], 3)):
        c = sev_color.get(sev, "#999")
        weaknesses.append(f'<span style="color:{c};font-weight:600">[{_esc(sev.upper())}]</span> '
                          f'{_esc(label)}{src("weaknesses", label)}')
    libs = []
    for name, ver, note in sorted(ex.libraries):
        if note:
            libs.append(f'<span class="bad">{_esc(name)} {_esc(ver)}</span> &mdash; {_esc(note)}')
        else:
            libs.append(f'{_esc(name)} {_esc(ver)}')
    interesting = [f'<code>{_esc(e)}</code>{src("endpoints", e)}'
                   for e in sorted(_interesting(ex.endpoints))]
    notable = [f'{_esc(n)}{src("notable", n)}' for n in sorted(ex.notable)]
    hosts = [f'<code>{_esc(h)}</code>{src("internal_hosts", h)}' for h in sorted(ex.internal_hosts)]
    ws = [f'<code>{_esc(w)}</code>{src("websockets", w)}' for w in sorted(ex.websockets)]
    comments = [f'<code>{_esc(c)}</code>' for c in sorted(ex.comments)]
    srcfiles = [f'<code>{_esc(s)}</code>' for s in sorted(ex.source_files)]

    body = "".join([
        _section("Secrets", secrets, "#e44628"),
        _section("Cloud assets", cloud, "#e44628"),
        _section("Potential weaknesses (verify)", weaknesses, "#e44628"),
        _section("Libraries", libs, "#d8a800"),
        _section("Interesting endpoints", interesting, "#d8a800"),
        _section("Notable signals", notable, "#b46fd0"),
        _section("Internal hosts / IPs", hosts, "#d8a800"),
        _section("WebSockets", ws, "#38d1d7"),
        _section("Developer comments", comments, "#b46fd0"),
        _section("Recovered source files", srcfiles, "#38d1d7"),
    ])
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    total = len(ex.endpoints)
    return _TEMPLATE.format(target=_esc(target), body=body, stamp=stamp,
                            total=total, secrets=len(ex.secrets),
                            weak=len(ex.weaknesses))


def _interesting(endpoints):
    from .analyze import interesting_endpoints
    return interesting_endpoints(endpoints)


_TEMPLATE = """<!doctype html>
<html><head><meta charset="utf-8"><title>driftjs report — {target}</title>
<style>
 body{{background:#0d0e11;color:#d8dae0;font:14px/1.6 ui-monospace,Menlo,Consolas,monospace;margin:0;padding:40px}}
 .wrap{{max-width:920px;margin:0 auto}}
 h1{{color:#38d1d7;font-size:22px;margin:0 0 4px}}
 .meta{{color:#787a82;margin-bottom:28px}}
 .stats{{display:flex;gap:24px;margin:20px 0 32px}}
 .stat{{background:#16171c;border-radius:8px;padding:12px 18px}}
 .stat b{{display:block;font-size:22px;color:#e6e8ee}}
 .stat span{{color:#787a82;font-size:12px}}
 h2{{font-size:15px;color:#e6e8ee;padding-left:10px;margin:28px 0 10px}}
 .count{{color:#787a82;font-weight:400;font-size:12px}}
 ul{{list-style:none;padding:0;margin:0}}
 li{{padding:5px 10px;border-bottom:1px solid #191a1f;word-break:break-all}}
 code{{color:#9fd0d5}}
 .bad{{color:#e44628;font-weight:600}}
 .src{{color:#5a5c64;font-size:12px}}
 footer{{margin-top:40px;color:#5a5c64;font-size:12px}}
</style></head>
<body><div class="wrap">
<h1>driftjs report</h1>
<div class="meta">{target} &middot; {stamp}</div>
<div class="stats">
 <div class="stat"><b>{total}</b><span>endpoints</span></div>
 <div class="stat"><b>{secrets}</b><span>secrets</span></div>
 <div class="stat"><b>{weak}</b><span>weakness leads</span></div>
</div>
{body}
<footer>Generated by driftjs. Detection-only; findings are leads to verify, not confirmed bugs. Authorized targets only.</footer>
</div></body></html>
"""
